version: "3.7"
services:
  app:
    build:
      # args:
      #   user: root
      #   uid: 1000
      context: .
      dockerfile: Dockerfile
      args:
        user: www-data  # Não use 'root' por questões de segurança
        uid: 1000
    image: app-consultacpf
    container_name: app-consultacpf
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage:delegated
    networks:
      - consultacpf-network   
  db:
    image: mysql:8.0
    container_name: db-consultacpf
    restart: unless-stopped
    environment:
    
      MYSQL_DATABASE: consultacpf_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: dsasd3a231
      MYSQL_USER: consultacpf_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - consultacpf-network
    ports:
      - 3432:3006
  nginx:
    image: nginx:alpine
    container_name: nginx-consultacpf
    restart: unless-stopped
    ports:
      - 3434:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - consultacpf-network
  receita-scraper:
    image: buildkite/puppeteer:latest
    ports:
      - "3435:3000"
    volumes:
      - ./receita-scraper:/app
    working_dir: /app
    # command: sh -c "npm install && node server.js" #prod
    command: sh -c "npm install && npm run dev" # Alterado para usar npm run dev
    networks:
      - consultacpf-network
networks:
  consultacpf-network:
    driver: bridge