version: "3.7"
services:
  app:
    build:
      # args:
      #   user: root
      #   uid: 1000
      context: .
      dockerfile: Dockerfile
      args:
        user: www-data  # Não use 'root' por questões de segurança
        uid: 1000
    image: app-consultacpf
    container_name: app-consultacpf
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage:delegated
    networks:
      - consultacpf-network   
  db:
    mysql:
    image: mariadb:10.4
    container_name: facegate_db
    volumes:
      - $PWD/database:/var/lib/mysql
    restart: unless-stopped
    environment:
    MYSQL_DATABASE: consultacpf_db
    MYSQL_ROOT_PASSWORD: 12#y3asd12#3rout
    MYSQL_PASSWORD: 12#y3asd12#3
    MYSQL_USER: consultacpf_user
    MYSQL_INITDB_SKIP_TZINFO: 1
    networks:
      - consultacpf-network
    ports:
      - 3432:300
  nginx:
    image: nginx:alpine
    container_name: nginx-consultacpf
    restart: unless-stopped
    ports:
      - 3434:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - consultacpf-network
  receita-scraper:
    image: buildkite/puppeteer:latest
    ports:
      - "3435:3000"
    volumes:
      - ./receita-scraper:/app
    working_dir: /app
    # command: sh -c "npm install && node server.js" #prod
    command: sh -c "npm install && npm run dev" # Alterado para usar npm run dev
    networks:
      - consultacpf-network
networks:
  consultacpf-network:
    driver: bridge
volumes:
  mysql_data: