FROM mcr.microsoft.com/playwright:v1.44.0-jammy

# 🔽 Limita uso de threads e memória (válido)
ENV UV_THREADPOOL_SIZE=1
ENV NODE_OPTIONS="--max-old-space-size=512"
ENV NODE_ENV=production


WORKDIR /app

COPY package*.json ./

#RUN npm install --no-audit --no-fund --foreground-scripts
RUN npm ci --no-audit --no-fund && npx playwright install webkit
#RUN npm ci --omit=dev --no-audit --no-fund

COPY . .

CMD ["npm", "run", "dev"]

